## Paola Díaz Serrano
# Parte 1: Creación y manipulación de arrays

In [2]:
import numpy as np

In [5]:
# Crear matriz
array = np.random.randint(1, 101, size=10)
print(array)

[ 76 100  75  84  98  30  99  64  19  18]


## Reshape

In [7]:
matriz = array.reshape(2, 5)
print (matriz)

[[ 76 100  75  84  98]
 [ 30  99  64  19  18]]


## Indexación y slicing
Extraer primer fila

In [8]:
primer_fila = matriz[0,:]
print(primer_fila)

[ 76 100  75  84  98]


Extraer última columna

In [9]:
ult_colum = matriz[:, -1]
print(ult_colum)

[98 18]


## Modificación

In [11]:
# Cambiar la segunda fila a ceros
matriz[1, :] = 0
print(matriz)

[[ 76 100  75  84  98]
 [  0   0   0   0   0]]


# Parte 2: Operaciones básicas con NumPy 

## Creación de arrays

In [26]:
# Creación de arrays
ar1 = np.random.randint(1, 51, size=5)
ar2 = np.random.randint(1, 51, size=5)
print("ar1 = ", ar1)
print("ar2 = ", ar2)

ar1 =  [40 30 50 25 18]
ar2 =  [49 38 24 42 10]


## Operaciones aritméticas 
Suma de arrays

In [27]:
#Suma de arrays
sum = ar1 +ar2

print("la suma de los arrays es: " ,sum)

la suma de los arrays es:  [89 68 74 67 28]


In [28]:
#Multiplicar arrays
mult = ar1 * ar2

print("Multiplicación: ", mult)

Multiplicación:  [1960 1140 1200 1050  180]


## Promedio y desviación

In [31]:
#Promedio de la suma
promedio_suma = np.mean(sum)
desviacion_suma = np.std(sum)

print("Promedio de la suma de arrays: ",promedio_suma)
print("Desviación de la suma de arrays: ",desviacion_suma)

Promedio de la suma de arrays:  65.2
Desviación de la suma de arrays:  20.193068117549647


In [32]:
#Promedio de la suma
promedio_mult = np.mean(mult)
desviacion_mult = np.std(mult)

print("Promedio de la mult de arrays: ",promedio_mult)
print("Desviación de la mult de arrays: ",desviacion_mult)

Promedio de la mult de arrays:  1106.0
Desviación de la mult de arrays:  565.6712826368332


## Condiciones lógicas

In [41]:
array_1 = np.random.rand(20)

array_1[array_1 < 0.5] = 0
array_1[array_1 >= 0.5] = 1

array_sin_punto = array_1.astype(int)
print(array_sin_punto)


[1 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1]


## Producto escalar

In [60]:
array1 = np.random.rand(3, 3)
array2 = np.random.rand(3, 3)

producto_escalar = np.dot(array1, array2)

print("Array 1: ", array1)
print("Array 2: ", array2)

print("Producto escalar: " , producto_escalar)

Array 1:  [[0.73769156 0.32587183 0.27933084]
 [0.46215176 0.00174702 0.22345534]
 [0.42739531 0.81332767 0.34990918]]
Array 2:  [[0.74219347 0.36048078 0.0987835 ]
 [0.76036348 0.9178195  0.10108294]
 [0.41052297 0.79087543 0.30340833]]
Producto escalar:  [[0.90996262 0.78593105 0.19056314]
 [0.43606794 0.34492562 0.11362777]
 [1.07928043 1.17729037 0.23059852]]


# Parte 3: Análisis de datos
Crear array(datos)

In [53]:
datos = np.random.randint(1, 21, size=(5, 4))

print(datos)

[[19  6 17 11]
 [ 7 11  7 12]
 [14  5  6 15]
 [ 9 20 16 20]
 [16 20  1  6]]


### Media

In [51]:
# Calcular la media
media_datos_columnas = np.mean(datos, axis=0)

print("Medición):", media_datos_columnas)

Medición): [ 6.  12.2  9.8 13.6]


### Valor mínimo y máximo

In [54]:
# Máximo de fila
max_filas = np.max(datos, axis=1)

# Encontrar el valor mínimo de cada fila
min_filas = np.min(datos, axis=1)

# Imprimir los resultados
for i in range(datos.shape[0]):
    print(f"Fila {i + 1}: Máximo = {max_filas[i]}, Mínimo = {min_filas[i]}")


Fila 1: Máximo = 19, Mínimo = 6
Fila 2: Máximo = 12, Mínimo = 7
Fila 3: Máximo = 15, Mínimo = 5
Fila 4: Máximo = 20, Mínimo = 9
Fila 5: Máximo = 20, Mínimo = 1


### Ordenar de acuerdo al peso

In [57]:
i_ordenados = np.argsort(datos[:, 1])
matriz_orden = datos[i_ordenados]

print("Matriz ordenada según peso orden descendente:", matriz_orden)

Matriz ordenada según peso orden descendente: [[14  5  6 15]
 [19  6 17 11]
 [ 7 11  7 12]
 [ 9 20 16 20]
 [16 20  1  6]]
